[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.default]
clear = true
dependencies = ["build"]

[tasks.build]
command = "wasm-pack"
install_crate = "wasm-pack"
args = [
    "build",
    "--dev",
    "--target",
    "web",
    "--out-name",
    "wasm",
    "--out-dir",
    "./resources/pkg",
]
watch = { ignore_pattern = "resources/*" }

[tasks.serve]
command = "miniserve"
install_crate = "miniserve"
args = ["-p", "5500", "./resources", "--index", "index.html"]
